### ISSUE TITLE
categorical discriminator loss compared with 1

### ISSUE THREAD

**Issue by nathanin** [Naresh1318/Adversarial_Autoencoder#1]
https://github.com/Naresh1318/Adversarial_Autoencoder/blob/2680a2b271d85cd84fbdbb18cb668cd4c9057489/semi_supervised_adversarial_autoencoder.py#L235-L236

Hi, I'm trying to implement the adversarial autoencoder myself. I found this repo and use it as a guide. It trains the autoencoder part but I think this line is a bug? Shouldn't the categorical discriminator train like the gaussian one? If it's not a bug could you comment on the training objective? Thanks!

**Comment by Naresh1318** [comment]
Hey!

That is indeed an error from my part, I have fixed it. 
Thank you for pointing it out!
