### ISSUE TITLE
The tools to draw network structure in readme file

### ISSUE THREAD

**Issue by dragen1860** [Naresh1318/Adversarial_Autoencoder#8]
Hi, dear author:
  I found the first diagram, dense network structure in your readme file is not generate by TF. Hence i wonder which tools you used to draw it?

**Comment by prclibo** [comment]
@dragen1860 Had the same question as you and found this:
https://medium.com/@rnaresh.n/hi-5523527d412e

> Naresh Nagabushan
Aug 31, 2017
Hi,
I used Adobe Illustrator for the block diagrams and the plots are from Tensorboard with some minor modifications.
